export const agentFaqItems = [
  ["What are the charges or fees for IRCTC agent registration?", "Registration charges start at ₹500 + GST, with OTP and DSC login options."],
  ["What are the benefits of registering as an IRCTC agent?", "Agents can book unlimited tickets, earn on PNRs, and offer other travel services."],
  ["What documents are required for IRCTC agent registration?", "You need PAN, Aadhaar, address proof, a fresh mobile number, and a unique email ID."],
  ["Can IRCTC agents book opening and Tatkal tickets?", "Yes, agents can book after the applicable IRCTC agent opening-time restriction."],
  ["Is there any special or additional seat quota for agents?", "No. Agents use the same live inventory and seat availability as other users."],
  ["What is the online link for IRCTC agent registration?", "You can complete the application through the TravelIQ registration portal."],
  ["How do I become an IRCTC agent?", "Complete the form, pay the fee, submit documents, complete verification, and receive your login."],
  ["How long does IRCTC agent registration take?", "OTP-based activation generally takes two working days; DSC activation can take longer."],
  ["What is an OTP-based IRCTC agent login?", "It lets you log in from supported devices using a one-time password sent to your registered mobile."],
  ["How do I get an IRCTC agent login?", "Apply through an authorized Principal Service Provider, submit documents, and complete verification."],
  ["Does IRCTC create booking agents directly?", "Agents register through authorized Principal Service Providers."],
  ["What is the office address of IRCTC?", "IRCTC's registered office is at Statesman House, Barakhamba Road, New Delhi."],
  ["How many Tatkal tickets can an IRCTC agent book?", "Agent Tatkal booking is subject to current IRCTC rules and time restrictions."],
  ["What is the full form of IRCTC?", "Indian Railway Catering and Tourism Corporation."],
  ["Where can I find the IRCTC agent service provider list?", "Use the official IRCTC Principal Service Provider directory to verify providers."],
  ["Can I start selling train tickets from home?", "Yes, if you complete agent registration and provide the required residential address proof."],
  ["Do I need a trade licence to become an IRCTC agent?", "No separate trade licence is required for individual agent registration."],
  ["Is GST registration compulsory for an IRCTC agent?", "GST registration is not compulsory for individual IRCTC agents."],
  ["Which operating system is required for IRCTC agent login?", "Use a current supported browser and device; DSC login has additional platform requirements."],
  ["Does macOS support DSC-based authentication?", "macOS does not support the USB dongle workflow; choose OTP login instead."],
  ["Can I book Premium Tatkal tickets on an agent login?", "Premium Tatkal booking is subject to IRCTC rules and restrictions."],
  ["How do I get the IRCTC agent registration form PDF?", "TravelIQ supports online registration; form and document guidance are available on the site."],
  ["Which states are available for IRCTC agent registration?", "TravelIQ supports registration across India, including states and Union Territories."],
  ["How do I remove a PAN card from a personal IRCTC account?", "In IRCTC, use My Account, My Profile, and the PAN/Aadhaar release option."],
].map(([question, answer]) => ({ question, answer }));
